// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  ethereum,
  JSONValue,
  TypedMap,
  Entity,
  Bytes,
  Address,
  BigInt
} from "@graphprotocol/graph-ts";

export class LOG_CALL extends ethereum.Event {
  get params(): LOG_CALL__Params {
    return new LOG_CALL__Params(this);
  }
}

export class LOG_CALL__Params {
  _event: LOG_CALL;

  constructor(event: LOG_CALL) {
    this._event = event;
  }

  get sig(): Bytes {
    return this._event.parameters[0].value.toBytes();
  }

  get caller(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get data(): Bytes {
    return this._event.parameters[2].value.toBytes();
  }
}

export class LOG_MIDDLEWARE extends ethereum.Event {
  get params(): LOG_MIDDLEWARE__Params {
    return new LOG_MIDDLEWARE__Params(this);
  }
}

export class LOG_MIDDLEWARE__Params {
  _event: LOG_MIDDLEWARE;

  constructor(event: LOG_MIDDLEWARE) {
    this._event = event;
  }

  get middleware(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get caller(): Address {
    return this._event.parameters[1].value.toAddress();
  }
}

export class LOG_USER_VAULT extends ethereum.Event {
  get params(): LOG_USER_VAULT__Params {
    return new LOG_USER_VAULT__Params(this);
  }
}

export class LOG_USER_VAULT__Params {
  _event: LOG_USER_VAULT;

  constructor(event: LOG_USER_VAULT) {
    this._event = event;
  }

  get vault(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get caller(): Address {
    return this._event.parameters[1].value.toAddress();
  }
}

export class LogNewCrp extends ethereum.Event {
  get params(): LogNewCrp__Params {
    return new LogNewCrp__Params(this);
  }
}

export class LogNewCrp__Params {
  _event: LogNewCrp;

  constructor(event: LogNewCrp) {
    this._event = event;
  }

  get caller(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get pool(): Address {
    return this._event.parameters[1].value.toAddress();
  }
}

export class CRPFactory__newCrpInputPoolParamsStruct extends ethereum.Tuple {
  get poolTokenSymbol(): string {
    return this[0].toString();
  }

  get poolTokenName(): string {
    return this[1].toString();
  }

  get constituentTokens(): Array<Address> {
    return this[2].toAddressArray();
  }

  get tokenBalances(): Array<BigInt> {
    return this[3].toBigIntArray();
  }

  get tokenWeights(): Array<BigInt> {
    return this[4].toBigIntArray();
  }

  get managerFee(): BigInt {
    return this[5].toBigInt();
  }

  get redeemFee(): BigInt {
    return this[6].toBigInt();
  }

  get issueFee(): BigInt {
    return this[7].toBigInt();
  }

  get perfermanceFee(): BigInt {
    return this[8].toBigInt();
  }

  get etype(): i32 {
    return this[9].toI32();
  }
}

export class CRPFactory__newCrpInputRightsStruct extends ethereum.Tuple {
  get canWhitelistLPs(): boolean {
    return this[0].toBoolean();
  }

  get canTokenWhiteLists(): boolean {
    return this[1].toBoolean();
  }
}

export class CRPFactory__newCrpInputKolPoolParamsStruct extends ethereum.Tuple {
  get managerFee(): CRPFactory__newCrpInputKolPoolParamsManagerFeeStruct {
    return this[0].toTuple() as CRPFactory__newCrpInputKolPoolParamsManagerFeeStruct;
  }

  get issueFee(): CRPFactory__newCrpInputKolPoolParamsIssueFeeStruct {
    return this[1].toTuple() as CRPFactory__newCrpInputKolPoolParamsIssueFeeStruct;
  }

  get redeemFee(): CRPFactory__newCrpInputKolPoolParamsRedeemFeeStruct {
    return this[2].toTuple() as CRPFactory__newCrpInputKolPoolParamsRedeemFeeStruct;
  }

  get perfermanceFee(): CRPFactory__newCrpInputKolPoolParamsPerfermanceFeeStruct {
    return this[3].toTuple() as CRPFactory__newCrpInputKolPoolParamsPerfermanceFeeStruct;
  }
}

export class CRPFactory__newCrpInputKolPoolParamsManagerFeeStruct extends ethereum.Tuple {
  get firstLevel(): CRPFactory__newCrpInputKolPoolParamsManagerFeeFirstLevelStruct {
    return this[0].toTuple() as CRPFactory__newCrpInputKolPoolParamsManagerFeeFirstLevelStruct;
  }

  get secondLevel(): CRPFactory__newCrpInputKolPoolParamsManagerFeeSecondLevelStruct {
    return this[1].toTuple() as CRPFactory__newCrpInputKolPoolParamsManagerFeeSecondLevelStruct;
  }

  get thirdLevel(): CRPFactory__newCrpInputKolPoolParamsManagerFeeThirdLevelStruct {
    return this[2].toTuple() as CRPFactory__newCrpInputKolPoolParamsManagerFeeThirdLevelStruct;
  }

  get fourLevel(): CRPFactory__newCrpInputKolPoolParamsManagerFeeFourLevelStruct {
    return this[3].toTuple() as CRPFactory__newCrpInputKolPoolParamsManagerFeeFourLevelStruct;
  }
}

export class CRPFactory__newCrpInputKolPoolParamsManagerFeeFirstLevelStruct extends ethereum.Tuple {
  get level(): BigInt {
    return this[0].toBigInt();
  }

  get ratio(): BigInt {
    return this[1].toBigInt();
  }
}

export class CRPFactory__newCrpInputKolPoolParamsManagerFeeSecondLevelStruct extends ethereum.Tuple {
  get level(): BigInt {
    return this[0].toBigInt();
  }

  get ratio(): BigInt {
    return this[1].toBigInt();
  }
}

export class CRPFactory__newCrpInputKolPoolParamsManagerFeeThirdLevelStruct extends ethereum.Tuple {
  get level(): BigInt {
    return this[0].toBigInt();
  }

  get ratio(): BigInt {
    return this[1].toBigInt();
  }
}

export class CRPFactory__newCrpInputKolPoolParamsManagerFeeFourLevelStruct extends ethereum.Tuple {
  get level(): BigInt {
    return this[0].toBigInt();
  }

  get ratio(): BigInt {
    return this[1].toBigInt();
  }
}

export class CRPFactory__newCrpInputKolPoolParamsIssueFeeStruct extends ethereum.Tuple {
  get firstLevel(): CRPFactory__newCrpInputKolPoolParamsIssueFeeFirstLevelStruct {
    return this[0].toTuple() as CRPFactory__newCrpInputKolPoolParamsIssueFeeFirstLevelStruct;
  }

  get secondLevel(): CRPFactory__newCrpInputKolPoolParamsIssueFeeSecondLevelStruct {
    return this[1].toTuple() as CRPFactory__newCrpInputKolPoolParamsIssueFeeSecondLevelStruct;
  }

  get thirdLevel(): CRPFactory__newCrpInputKolPoolParamsIssueFeeThirdLevelStruct {
    return this[2].toTuple() as CRPFactory__newCrpInputKolPoolParamsIssueFeeThirdLevelStruct;
  }

  get fourLevel(): CRPFactory__newCrpInputKolPoolParamsIssueFeeFourLevelStruct {
    return this[3].toTuple() as CRPFactory__newCrpInputKolPoolParamsIssueFeeFourLevelStruct;
  }
}

export class CRPFactory__newCrpInputKolPoolParamsIssueFeeFirstLevelStruct extends ethereum.Tuple {
  get level(): BigInt {
    return this[0].toBigInt();
  }

  get ratio(): BigInt {
    return this[1].toBigInt();
  }
}

export class CRPFactory__newCrpInputKolPoolParamsIssueFeeSecondLevelStruct extends ethereum.Tuple {
  get level(): BigInt {
    return this[0].toBigInt();
  }

  get ratio(): BigInt {
    return this[1].toBigInt();
  }
}

export class CRPFactory__newCrpInputKolPoolParamsIssueFeeThirdLevelStruct extends ethereum.Tuple {
  get level(): BigInt {
    return this[0].toBigInt();
  }

  get ratio(): BigInt {
    return this[1].toBigInt();
  }
}

export class CRPFactory__newCrpInputKolPoolParamsIssueFeeFourLevelStruct extends ethereum.Tuple {
  get level(): BigInt {
    return this[0].toBigInt();
  }

  get ratio(): BigInt {
    return this[1].toBigInt();
  }
}

export class CRPFactory__newCrpInputKolPoolParamsRedeemFeeStruct extends ethereum.Tuple {
  get firstLevel(): CRPFactory__newCrpInputKolPoolParamsRedeemFeeFirstLevelStruct {
    return this[0].toTuple() as CRPFactory__newCrpInputKolPoolParamsRedeemFeeFirstLevelStruct;
  }

  get secondLevel(): CRPFactory__newCrpInputKolPoolParamsRedeemFeeSecondLevelStruct {
    return this[1].toTuple() as CRPFactory__newCrpInputKolPoolParamsRedeemFeeSecondLevelStruct;
  }

  get thirdLevel(): CRPFactory__newCrpInputKolPoolParamsRedeemFeeThirdLevelStruct {
    return this[2].toTuple() as CRPFactory__newCrpInputKolPoolParamsRedeemFeeThirdLevelStruct;
  }

  get fourLevel(): CRPFactory__newCrpInputKolPoolParamsRedeemFeeFourLevelStruct {
    return this[3].toTuple() as CRPFactory__newCrpInputKolPoolParamsRedeemFeeFourLevelStruct;
  }
}

export class CRPFactory__newCrpInputKolPoolParamsRedeemFeeFirstLevelStruct extends ethereum.Tuple {
  get level(): BigInt {
    return this[0].toBigInt();
  }

  get ratio(): BigInt {
    return this[1].toBigInt();
  }
}

export class CRPFactory__newCrpInputKolPoolParamsRedeemFeeSecondLevelStruct extends ethereum.Tuple {
  get level(): BigInt {
    return this[0].toBigInt();
  }

  get ratio(): BigInt {
    return this[1].toBigInt();
  }
}

export class CRPFactory__newCrpInputKolPoolParamsRedeemFeeThirdLevelStruct extends ethereum.Tuple {
  get level(): BigInt {
    return this[0].toBigInt();
  }

  get ratio(): BigInt {
    return this[1].toBigInt();
  }
}

export class CRPFactory__newCrpInputKolPoolParamsRedeemFeeFourLevelStruct extends ethereum.Tuple {
  get level(): BigInt {
    return this[0].toBigInt();
  }

  get ratio(): BigInt {
    return this[1].toBigInt();
  }
}

export class CRPFactory__newCrpInputKolPoolParamsPerfermanceFeeStruct extends ethereum.Tuple {
  get firstLevel(): CRPFactory__newCrpInputKolPoolParamsPerfermanceFeeFirstLevelStruct {
    return this[0].toTuple() as CRPFactory__newCrpInputKolPoolParamsPerfermanceFeeFirstLevelStruct;
  }

  get secondLevel(): CRPFactory__newCrpInputKolPoolParamsPerfermanceFeeSecondLevelStruct {
    return this[1].toTuple() as CRPFactory__newCrpInputKolPoolParamsPerfermanceFeeSecondLevelStruct;
  }

  get thirdLevel(): CRPFactory__newCrpInputKolPoolParamsPerfermanceFeeThirdLevelStruct {
    return this[2].toTuple() as CRPFactory__newCrpInputKolPoolParamsPerfermanceFeeThirdLevelStruct;
  }

  get fourLevel(): CRPFactory__newCrpInputKolPoolParamsPerfermanceFeeFourLevelStruct {
    return this[3].toTuple() as CRPFactory__newCrpInputKolPoolParamsPerfermanceFeeFourLevelStruct;
  }
}

export class CRPFactory__newCrpInputKolPoolParamsPerfermanceFeeFirstLevelStruct extends ethereum.Tuple {
  get level(): BigInt {
    return this[0].toBigInt();
  }

  get ratio(): BigInt {
    return this[1].toBigInt();
  }
}

export class CRPFactory__newCrpInputKolPoolParamsPerfermanceFeeSecondLevelStruct extends ethereum.Tuple {
  get level(): BigInt {
    return this[0].toBigInt();
  }

  get ratio(): BigInt {
    return this[1].toBigInt();
  }
}

export class CRPFactory__newCrpInputKolPoolParamsPerfermanceFeeThirdLevelStruct extends ethereum.Tuple {
  get level(): BigInt {
    return this[0].toBigInt();
  }

  get ratio(): BigInt {
    return this[1].toBigInt();
  }
}

export class CRPFactory__newCrpInputKolPoolParamsPerfermanceFeeFourLevelStruct extends ethereum.Tuple {
  get level(): BigInt {
    return this[0].toBigInt();
  }

  get ratio(): BigInt {
    return this[1].toBigInt();
  }
}

export class CRPFactory extends ethereum.SmartContract {
  static bind(address: Address): CRPFactory {
    return new CRPFactory("CRPFactory", address);
  }

  bytecodes(): Bytes {
    let result = super.call("bytecodes", "bytecodes():(bytes)", []);

    return result[0].toBytes();
  }

  try_bytecodes(): ethereum.CallResult<Bytes> {
    let result = super.tryCall("bytecodes", "bytecodes():(bytes)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBytes());
  }

  isCrp(addr: Address): boolean {
    let result = super.call("isCrp", "isCrp(address):(bool)", [
      ethereum.Value.fromAddress(addr)
    ]);

    return result[0].toBoolean();
  }

  try_isCrp(addr: Address): ethereum.CallResult<boolean> {
    let result = super.tryCall("isCrp", "isCrp(address):(bool)", [
      ethereum.Value.fromAddress(addr)
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBoolean());
  }

  newCrp(
    factoryAddress: Address,
    poolParams: CRPFactory__newCrpInputPoolParamsStruct,
    rights: CRPFactory__newCrpInputRightsStruct,
    kolPoolParams: CRPFactory__newCrpInputKolPoolParamsStruct,
    owners: Array<Address>,
    ownerPercentage: Array<BigInt>
  ): Address {
    let result = super.call(
      "newCrp",
      "newCrp(address,(string,string,address[],uint256[],uint256[],uint256,uint256,uint256,uint256,uint8),(bool,bool),(((uint256,uint256),(uint256,uint256),(uint256,uint256),(uint256,uint256)),((uint256,uint256),(uint256,uint256),(uint256,uint256),(uint256,uint256)),((uint256,uint256),(uint256,uint256),(uint256,uint256),(uint256,uint256)),((uint256,uint256),(uint256,uint256),(uint256,uint256),(uint256,uint256))),address[],uint256[]):(address)",
      [
        ethereum.Value.fromAddress(factoryAddress),
        ethereum.Value.fromTuple(poolParams),
        ethereum.Value.fromTuple(rights),
        ethereum.Value.fromTuple(kolPoolParams),
        ethereum.Value.fromAddressArray(owners),
        ethereum.Value.fromUnsignedBigIntArray(ownerPercentage)
      ]
    );

    return result[0].toAddress();
  }

  try_newCrp(
    factoryAddress: Address,
    poolParams: CRPFactory__newCrpInputPoolParamsStruct,
    rights: CRPFactory__newCrpInputRightsStruct,
    kolPoolParams: CRPFactory__newCrpInputKolPoolParamsStruct,
    owners: Array<Address>,
    ownerPercentage: Array<BigInt>
  ): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "newCrp",
      "newCrp(address,(string,string,address[],uint256[],uint256[],uint256,uint256,uint256,uint256,uint8),(bool,bool),(((uint256,uint256),(uint256,uint256),(uint256,uint256),(uint256,uint256)),((uint256,uint256),(uint256,uint256),(uint256,uint256),(uint256,uint256)),((uint256,uint256),(uint256,uint256),(uint256,uint256),(uint256,uint256)),((uint256,uint256),(uint256,uint256),(uint256,uint256),(uint256,uint256))),address[],uint256[]):(address)",
      [
        ethereum.Value.fromAddress(factoryAddress),
        ethereum.Value.fromTuple(poolParams),
        ethereum.Value.fromTuple(rights),
        ethereum.Value.fromTuple(kolPoolParams),
        ethereum.Value.fromAddressArray(owners),
        ethereum.Value.fromUnsignedBigIntArray(ownerPercentage)
      ]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  userVault(): Address {
    let result = super.call("userVault", "userVault():(address)", []);

    return result[0].toAddress();
  }

  try_userVault(): ethereum.CallResult<Address> {
    let result = super.tryCall("userVault", "userVault():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }
}

export class ConstructorCall extends ethereum.Call {
  get inputs(): ConstructorCall__Inputs {
    return new ConstructorCall__Inputs(this);
  }

  get outputs(): ConstructorCall__Outputs {
    return new ConstructorCall__Outputs(this);
  }
}

export class ConstructorCall__Inputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }

  get _bytecode(): Bytes {
    return this._call.inputValues[0].value.toBytes();
  }
}

export class ConstructorCall__Outputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }
}

export class NewCrpCall extends ethereum.Call {
  get inputs(): NewCrpCall__Inputs {
    return new NewCrpCall__Inputs(this);
  }

  get outputs(): NewCrpCall__Outputs {
    return new NewCrpCall__Outputs(this);
  }
}

export class NewCrpCall__Inputs {
  _call: NewCrpCall;

  constructor(call: NewCrpCall) {
    this._call = call;
  }

  get factoryAddress(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get poolParams(): NewCrpCallPoolParamsStruct {
    return this._call.inputValues[1].value.toTuple() as NewCrpCallPoolParamsStruct;
  }

  get rights(): NewCrpCallRightsStruct {
    return this._call.inputValues[2].value.toTuple() as NewCrpCallRightsStruct;
  }

  get kolPoolParams(): NewCrpCallKolPoolParamsStruct {
    return this._call.inputValues[3].value.toTuple() as NewCrpCallKolPoolParamsStruct;
  }

  get owners(): Array<Address> {
    return this._call.inputValues[4].value.toAddressArray();
  }

  get ownerPercentage(): Array<BigInt> {
    return this._call.inputValues[5].value.toBigIntArray();
  }
}

export class NewCrpCall__Outputs {
  _call: NewCrpCall;

  constructor(call: NewCrpCall) {
    this._call = call;
  }

  get value0(): Address {
    return this._call.outputValues[0].value.toAddress();
  }
}

export class NewCrpCallPoolParamsStruct extends ethereum.Tuple {
  get poolTokenSymbol(): string {
    return this[0].toString();
  }

  get poolTokenName(): string {
    return this[1].toString();
  }

  get constituentTokens(): Array<Address> {
    return this[2].toAddressArray();
  }

  get tokenBalances(): Array<BigInt> {
    return this[3].toBigIntArray();
  }

  get tokenWeights(): Array<BigInt> {
    return this[4].toBigIntArray();
  }

  get managerFee(): BigInt {
    return this[5].toBigInt();
  }

  get redeemFee(): BigInt {
    return this[6].toBigInt();
  }

  get issueFee(): BigInt {
    return this[7].toBigInt();
  }

  get perfermanceFee(): BigInt {
    return this[8].toBigInt();
  }

  get etype(): i32 {
    return this[9].toI32();
  }
}

export class NewCrpCallRightsStruct extends ethereum.Tuple {
  get canWhitelistLPs(): boolean {
    return this[0].toBoolean();
  }

  get canTokenWhiteLists(): boolean {
    return this[1].toBoolean();
  }
}

export class NewCrpCallKolPoolParamsStruct extends ethereum.Tuple {
  get managerFee(): NewCrpCallKolPoolParamsManagerFeeStruct {
    return this[0].toTuple() as NewCrpCallKolPoolParamsManagerFeeStruct;
  }

  get issueFee(): NewCrpCallKolPoolParamsIssueFeeStruct {
    return this[1].toTuple() as NewCrpCallKolPoolParamsIssueFeeStruct;
  }

  get redeemFee(): NewCrpCallKolPoolParamsRedeemFeeStruct {
    return this[2].toTuple() as NewCrpCallKolPoolParamsRedeemFeeStruct;
  }

  get perfermanceFee(): NewCrpCallKolPoolParamsPerfermanceFeeStruct {
    return this[3].toTuple() as NewCrpCallKolPoolParamsPerfermanceFeeStruct;
  }
}

export class NewCrpCallKolPoolParamsManagerFeeStruct extends ethereum.Tuple {
  get firstLevel(): NewCrpCallKolPoolParamsManagerFeeFirstLevelStruct {
    return this[0].toTuple() as NewCrpCallKolPoolParamsManagerFeeFirstLevelStruct;
  }

  get secondLevel(): NewCrpCallKolPoolParamsManagerFeeSecondLevelStruct {
    return this[1].toTuple() as NewCrpCallKolPoolParamsManagerFeeSecondLevelStruct;
  }

  get thirdLevel(): NewCrpCallKolPoolParamsManagerFeeThirdLevelStruct {
    return this[2].toTuple() as NewCrpCallKolPoolParamsManagerFeeThirdLevelStruct;
  }

  get fourLevel(): NewCrpCallKolPoolParamsManagerFeeFourLevelStruct {
    return this[3].toTuple() as NewCrpCallKolPoolParamsManagerFeeFourLevelStruct;
  }
}

export class NewCrpCallKolPoolParamsManagerFeeFirstLevelStruct extends ethereum.Tuple {
  get level(): BigInt {
    return this[0].toBigInt();
  }

  get ratio(): BigInt {
    return this[1].toBigInt();
  }
}

export class NewCrpCallKolPoolParamsManagerFeeSecondLevelStruct extends ethereum.Tuple {
  get level(): BigInt {
    return this[0].toBigInt();
  }

  get ratio(): BigInt {
    return this[1].toBigInt();
  }
}

export class NewCrpCallKolPoolParamsManagerFeeThirdLevelStruct extends ethereum.Tuple {
  get level(): BigInt {
    return this[0].toBigInt();
  }

  get ratio(): BigInt {
    return this[1].toBigInt();
  }
}

export class NewCrpCallKolPoolParamsManagerFeeFourLevelStruct extends ethereum.Tuple {
  get level(): BigInt {
    return this[0].toBigInt();
  }

  get ratio(): BigInt {
    return this[1].toBigInt();
  }
}

export class NewCrpCallKolPoolParamsIssueFeeStruct extends ethereum.Tuple {
  get firstLevel(): NewCrpCallKolPoolParamsIssueFeeFirstLevelStruct {
    return this[0].toTuple() as NewCrpCallKolPoolParamsIssueFeeFirstLevelStruct;
  }

  get secondLevel(): NewCrpCallKolPoolParamsIssueFeeSecondLevelStruct {
    return this[1].toTuple() as NewCrpCallKolPoolParamsIssueFeeSecondLevelStruct;
  }

  get thirdLevel(): NewCrpCallKolPoolParamsIssueFeeThirdLevelStruct {
    return this[2].toTuple() as NewCrpCallKolPoolParamsIssueFeeThirdLevelStruct;
  }

  get fourLevel(): NewCrpCallKolPoolParamsIssueFeeFourLevelStruct {
    return this[3].toTuple() as NewCrpCallKolPoolParamsIssueFeeFourLevelStruct;
  }
}

export class NewCrpCallKolPoolParamsIssueFeeFirstLevelStruct extends ethereum.Tuple {
  get level(): BigInt {
    return this[0].toBigInt();
  }

  get ratio(): BigInt {
    return this[1].toBigInt();
  }
}

export class NewCrpCallKolPoolParamsIssueFeeSecondLevelStruct extends ethereum.Tuple {
  get level(): BigInt {
    return this[0].toBigInt();
  }

  get ratio(): BigInt {
    return this[1].toBigInt();
  }
}

export class NewCrpCallKolPoolParamsIssueFeeThirdLevelStruct extends ethereum.Tuple {
  get level(): BigInt {
    return this[0].toBigInt();
  }

  get ratio(): BigInt {
    return this[1].toBigInt();
  }
}

export class NewCrpCallKolPoolParamsIssueFeeFourLevelStruct extends ethereum.Tuple {
  get level(): BigInt {
    return this[0].toBigInt();
  }

  get ratio(): BigInt {
    return this[1].toBigInt();
  }
}

export class NewCrpCallKolPoolParamsRedeemFeeStruct extends ethereum.Tuple {
  get firstLevel(): NewCrpCallKolPoolParamsRedeemFeeFirstLevelStruct {
    return this[0].toTuple() as NewCrpCallKolPoolParamsRedeemFeeFirstLevelStruct;
  }

  get secondLevel(): NewCrpCallKolPoolParamsRedeemFeeSecondLevelStruct {
    return this[1].toTuple() as NewCrpCallKolPoolParamsRedeemFeeSecondLevelStruct;
  }

  get thirdLevel(): NewCrpCallKolPoolParamsRedeemFeeThirdLevelStruct {
    return this[2].toTuple() as NewCrpCallKolPoolParamsRedeemFeeThirdLevelStruct;
  }

  get fourLevel(): NewCrpCallKolPoolParamsRedeemFeeFourLevelStruct {
    return this[3].toTuple() as NewCrpCallKolPoolParamsRedeemFeeFourLevelStruct;
  }
}

export class NewCrpCallKolPoolParamsRedeemFeeFirstLevelStruct extends ethereum.Tuple {
  get level(): BigInt {
    return this[0].toBigInt();
  }

  get ratio(): BigInt {
    return this[1].toBigInt();
  }
}

export class NewCrpCallKolPoolParamsRedeemFeeSecondLevelStruct extends ethereum.Tuple {
  get level(): BigInt {
    return this[0].toBigInt();
  }

  get ratio(): BigInt {
    return this[1].toBigInt();
  }
}

export class NewCrpCallKolPoolParamsRedeemFeeThirdLevelStruct extends ethereum.Tuple {
  get level(): BigInt {
    return this[0].toBigInt();
  }

  get ratio(): BigInt {
    return this[1].toBigInt();
  }
}

export class NewCrpCallKolPoolParamsRedeemFeeFourLevelStruct extends ethereum.Tuple {
  get level(): BigInt {
    return this[0].toBigInt();
  }

  get ratio(): BigInt {
    return this[1].toBigInt();
  }
}

export class NewCrpCallKolPoolParamsPerfermanceFeeStruct extends ethereum.Tuple {
  get firstLevel(): NewCrpCallKolPoolParamsPerfermanceFeeFirstLevelStruct {
    return this[0].toTuple() as NewCrpCallKolPoolParamsPerfermanceFeeFirstLevelStruct;
  }

  get secondLevel(): NewCrpCallKolPoolParamsPerfermanceFeeSecondLevelStruct {
    return this[1].toTuple() as NewCrpCallKolPoolParamsPerfermanceFeeSecondLevelStruct;
  }

  get thirdLevel(): NewCrpCallKolPoolParamsPerfermanceFeeThirdLevelStruct {
    return this[2].toTuple() as NewCrpCallKolPoolParamsPerfermanceFeeThirdLevelStruct;
  }

  get fourLevel(): NewCrpCallKolPoolParamsPerfermanceFeeFourLevelStruct {
    return this[3].toTuple() as NewCrpCallKolPoolParamsPerfermanceFeeFourLevelStruct;
  }
}

export class NewCrpCallKolPoolParamsPerfermanceFeeFirstLevelStruct extends ethereum.Tuple {
  get level(): BigInt {
    return this[0].toBigInt();
  }

  get ratio(): BigInt {
    return this[1].toBigInt();
  }
}

export class NewCrpCallKolPoolParamsPerfermanceFeeSecondLevelStruct extends ethereum.Tuple {
  get level(): BigInt {
    return this[0].toBigInt();
  }

  get ratio(): BigInt {
    return this[1].toBigInt();
  }
}

export class NewCrpCallKolPoolParamsPerfermanceFeeThirdLevelStruct extends ethereum.Tuple {
  get level(): BigInt {
    return this[0].toBigInt();
  }

  get ratio(): BigInt {
    return this[1].toBigInt();
  }
}

export class NewCrpCallKolPoolParamsPerfermanceFeeFourLevelStruct extends ethereum.Tuple {
  get level(): BigInt {
    return this[0].toBigInt();
  }

  get ratio(): BigInt {
    return this[1].toBigInt();
  }
}

export class SetByteCodesCall extends ethereum.Call {
  get inputs(): SetByteCodesCall__Inputs {
    return new SetByteCodesCall__Inputs(this);
  }

  get outputs(): SetByteCodesCall__Outputs {
    return new SetByteCodesCall__Outputs(this);
  }
}

export class SetByteCodesCall__Inputs {
  _call: SetByteCodesCall;

  constructor(call: SetByteCodesCall) {
    this._call = call;
  }

  get _bytecodes(): Bytes {
    return this._call.inputValues[0].value.toBytes();
  }
}

export class SetByteCodesCall__Outputs {
  _call: SetByteCodesCall;

  constructor(call: SetByteCodesCall) {
    this._call = call;
  }
}

export class SetUserVaultCall extends ethereum.Call {
  get inputs(): SetUserVaultCall__Inputs {
    return new SetUserVaultCall__Inputs(this);
  }

  get outputs(): SetUserVaultCall__Outputs {
    return new SetUserVaultCall__Outputs(this);
  }
}

export class SetUserVaultCall__Inputs {
  _call: SetUserVaultCall;

  constructor(call: SetUserVaultCall) {
    this._call = call;
  }

  get newVault(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class SetUserVaultCall__Outputs {
  _call: SetUserVaultCall;

  constructor(call: SetUserVaultCall) {
    this._call = call;
  }
}
